### PR TITLE
upgrade 2.12.2

### PR DESCRIPTION
**Pull request by mcharriere**
- Bump version 2.12.2
- changelog

This PR upgrades to version 2.12.2

Towards https://github.com/giantswarm/giantswarm/issues/23384

## Checklist

- [ ] Automated test are working (for chart changes)
- [ ] I am confident my changes don't break existing installations (for chart changes)
- [ ] Changelog entry has been added

### CODE REVIEW

**Review by webwurst — APPROVED** [review]

**Comment by Gacko** [comment]
I think there is some stuff for the postHookInitHack in the values.yaml also.

**Comment by mcharriere** [comment]
> I think there is some stuff for the postHookInitHack in the values.yaml also.

yes indeed, updated.

**Review by Gacko — APPROVED** [review]

**Review by ced0ps — APPROVED** [review]
LGTM

**Comment by mcharriere** [comment]
FYI, testing this PR I found that the `gcr.io/google_containers/pause` tries to run as root, which is not allowed. I'll fix that before merging

**Comment by mcharriere** [comment]
```
Linkerd core checks            
===================                   
                                                            
kubernetes-api               
--------------                          
√ can initialize the client
√ can query the Kubernetes API
                                                            
kubernetes-version           
------------------                                  
√ is running the minimum Kubernetes API version 
√ is running the minimum kubectl version      
                                                            
linkerd-existence                          
-----------------                          
√ 'linkerd-config' config map exists       
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods        
√ control plane pods are ready         
√ cluster networks contains all pods               
√ cluster networks contains all services
                                                            
linkerd-config                           
--------------                                       
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ proxy-init container runs as root user if docker container runtime is used
                                                            
linkerd-cni-plugin           
------------------                    
√ cni plugin ConfigMap exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin ServiceAccount exists 
√ cni plugin DaemonSet exists         
√ cni plugin pod is running on all nodes      

linkerd-identity 
---------------- 
√ certificate config is valid          
√ trust anchors are using supported crypto algorithm                                                                                                                                                                                               
√ trust anchors are within their validity period                                                                         
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period                                                                                                                                                                                                        
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ can retrieve the control plane version
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
√ control plane proxies are up-to-date
√ control plane proxies and cli versions match

linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if injector webhook failure policy is Fail
    see https://linkerd.io/2.12/checks/#l5d-injection-disabled for hints

Status check results are √
```

**Pull request merged**
