### PR TITLE
templates: Remove post hook init hack when CNI is disabled.

### PR DESCRIPTION
**Pull request by Gacko**
Didn't render anway...

- **This repository allows merge commits, if you're creating a Release, make sure to select 'Squash and merge'**
- **When merging subtree updates, it is important to select 'Create a merge commit' when merging.**

Title says it all. The hack is not required as long as there is another init container around.

## Checklist

- [x] Automated test are working (for chart changes)
- [x] I am confident my changes don't break existing installations (for chart changes)
- [x] Changelog entry has been added

### CODE REVIEW

**Comment by Gacko** [comment]
CC @pipo02mix. WDYT?

**Comment by Gacko** [comment]
No, you did not add the hack to the identity component at all.

**Comment by pipo02mix** [comment]
I thought so, but maybe not :D

**Review by pipo02mix — APPROVED** [review]
LGTM

**Pull request merged**
